declare namespace NodeJS {
  interface ProcessEnv {
    GATSBY_FIREBASE_API_KEY: string
    GATSBY_FIREBASE_AUTH_DOMAIN: string
    GATSBY_FIREBASE_DATABASE_URL: string
    GATSBY_FIREBASE_PROJECT_ID: string
    GATSBY_FIREBASE_STORAGE_BUCKET: string
    GATSBY_FIREBASE_MESSAGING_SENDER: string
    GATSBY_FIREBASE_APP_ID: string
    GATSBY_API_URL: string
    GATSBY_GOOGLE_ID: string
  }
}
